[package]
name = "bevy_djqf"
description = "Disjoint query filters for Bevy"
version = "0.1.0"
authors = ["tigregalis"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tigregalis/bevy_djqf"

[dependencies]
bevy_ecs = "0.14.1"

[dev-dependencies]
bevy = "0.14.1"
